

[enum]::getvalues([Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy17PD_IncidentInterface_Create_WS.Work_Info_SourceType])

$URI = 'C:\Users\abaker9\Documents\WindowsPowerShell\Modules\ServiceDesk\Files\HPD_IncidentInterface_WS.wsdl'
$URI = 'http://www.itsms.ford.com/arsys/WSDL/public/itsmsapp.ford.com/HPD_IncidentInterface_Create_WS'
       #http://www.itsms.ford.com/arsys/WSDL/public/eccvas1037/HPD_IncidentInterface_Create_WS
$proxy = New-AuthenticatedWebServiceProxy -credential $cred -URI $URL -Maxtries 2


New-Incident -credential $cred -ci_name 'fsilws10' -Summary 'Testing' -Notes 'here are the details' -verbose

New-Incident -credential $cred -ci_name 'fsilws10' -Summary 'Testing' -Notes 'here are the details' -URI 'http://wwwqa.itsms.ford.com/arsys/WSDL/public/eccvas1037/HPD_IncidentInterface_Create_WS'


$proxy|Get-Member|Where-Object membertype -eq Method

Get-ProxyMethodFields -proxy $proxy -Method HelpDesk_Submit_Service

# http://www.itsms.ford.com/arsys/WSDL/public/itsmsapp.ford.com/HPD_IncidentInterface_Create_WS


